### ISSUE TITLE
Scrape URL 部分链接会报错

### ISSUE THREAD

**Issue by JammyLin** [samyycX/CS2-BuffInspector#1]
![Snipaste_2024-04-17_20-09-36](https://github.com/samyycX/CS2-BuffInspector/assets/23147837/4baec8d0-efaf-4f35-98fa-36513225725e)

**Comment by samyycX** [comment]
暂不支持探员

**Comment by JammyLin** [comment]
如果有空的话可以写一下所需c#版本。
因为我第一次接触这语言，都是用的Console，有的话可以提供很大的帮助，感谢。

**Comment by samyycX** [comment]
> 如果有空的话可以写一下所需c#版本。 因为我第一次接触这语言，都是用的Console，有的话可以提供很大的帮助，感谢。

使用的是.NET 8
