### ISSUE TITLE
【BUG or ?】输入分享链接之后服务器崩溃（不是每一次都会）

### ISSUE THREAD

**Issue by DearCrazyLeaf** [samyycX/CS2-BuffInspector#3]
大佬好，我又来用你的插件了，这次我配置了wp插件之后，加了您的BUFF解析，然后换皮肤的时候有概率（较大）会导致服务器崩溃
weaponpaints插件我已经配置好了数据库，自建网站，等功能，buff解析插件关闭了自动刷新和贴纸功能以及预览视图，其他的默认。

以下是wp插件的cfg文件详细代码：
`{
  "Version": 6,
  "CmdRefreshCooldownSeconds": 5,
  "Prefix": "【{GREEN}黄粱一梦&废物乐园{Default}】",
  "Website": "http://teamkiller.top:27075/",
  "Additional": {
    "KnifeEnabled": true,
    "GloveEnabled": true,
    "MusicEnabled": false,
    "AgentEnabled": false,
    "SkinEnabled": true,
    "CommandWpEnabled": true,
    "CommandKillEnabled": false,
    "CommandKnife": "knife",
    "CommandMusic": "music",
    "CommandGlove": "gloves",
    "CommandAgent": "agents",
    "CommandSkin": "ws",
    "CommandSkinSelection": "skins",
    "CommandRefresh": "wp",
    "CommandKill": "kill",
    "GiveRandomKnife": false,
    "GiveRandomSkin": false,
    "ShowSkinImage": false
  },
  "ConfigVersion": 6
}`
另外我还有一个问题（不是关于此插件的），就是我搭建的网站点击登陆steam之后加载不出来，然后提示：
`InternalOpenIDError: Failed to discover OP endpoint URL
    at C:\Users\Administrator\Desktop\webside_html\webside_custom_skins\node_modules\@passport-next\passport-openid\lib\passport-openid\strategy.js:249:52
    at C:\Users\Administrator\Desktop\webside_html\webside_custom_skins\node_modules\openid\openid.js:757:14
    at C:\Users\Administrator\Desktop\webside_html\webside_custom_skins\node_modules\openid\openid.js:547:13
    at C:\Users\Administrator\Desktop\webside_html\webside_custom_skins\node_modules\openid\openid.js:503:11
    at C:\Users\Administrator\Desktop\webside_html\webside_custom_skins\node_modules\openid\http.js:41:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`
是否是因为无法登陆steam才导致的此问题？（服务器后台是可以访问steam社区以及登陆网页的）
数据库运行和显示玩家皮肤信息正常

如果可以的话能否请您提供一下远程或者聊天指导，QQ：2336758119

**Comment by DearCrazyLeaf** [comment]
![qq_pic_merged_1717696460535](https://github.com/samyycX/CS2-BuffInspector/assets/124550277/9b356edb-f77c-460e-967b-4e37fb537b5d)

后台报错

**Comment by samyycX** [comment]
**建议你把配置文件里的数据库信息隐藏，防止泄露**

关于崩溃的问题，请尝试删除gamedata文件夹中的BuffInspector.json，另外崩溃时请把报错记录截完整（在服务器启动项加 `-condebug` 后可以在 `./game/csgo/logs/` 文件夹里找到完整的日志）

另外你给的这个网站问题，一般情况还是网络问题（连的上steam社区也不一定能连上steam api），可以使用科学上网工具解决

**Comment by DearCrazyLeaf** [comment]
问题找到了，原因是连接到数据库延迟过高，导致写入不了数据服务器崩溃，在本机上搭了一个localhost数据库，问题得到了解决
