### ISSUE TITLE
无法加载插件MySqlConnector

### ISSUE THREAD

**Issue by BestBcz** [samyycX/CS2-BuffInspector#4]
放入服务器并重启后，输入！buff没有反应，所以用css_plugins reload 了一下，报错如下图：
![image](https://github.com/user-attachments/assets/1d91a757-b57e-4f69-88e7-f550e96de780)

**Comment by samyycX** [comment]
试一下 https://github.com/samyycX/CS2-BuffInspector/releases/tag/build-5
